---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-pagerduty-key
  namespace: monitoring
spec:
  encryptedData:
    integration-key: AgCAF4gZ3oKwsqO3PGSBmkbpRtJ3bHtvYDArdG3aLWd7NeOWtQbcAI8mpTeYLhJRI+mLS7mX2qcNHihC/jTEMsECdl3YaNvUHDnVUjV7XfMFpaiPZ4cU5b7xvg7uGWC171EBo7Rf2+HgQ/4p5DVfyO6jYGm4eJO5xWGMuH/mTaloXok8v8gem7vlbK4mrGwt6Ns80ROHqiQUbtshKgbAHUpg6FZWlGOnxdYVcNoWK+dgrXnNWxAfxaeK2qIsIlNCaqqHtsW8ndoXCZxJwruv6+HHNYt/a2yNOKl4+fZIH8waNZKqXrBglhJzHJkXbbB6ILOiBMnf46LoY6J3JpQmDKwmddJuGbxruiWUuIPpEcN9KXsmidcl0dxV3H/9Fg7lkXWgePHbXeD+3caL/LDkNDAs7TzCfQqTfWXRhz9EZHuuUGLvC2NOk56BtaWtnD5W51OPOfTWTVjeobpv7cM2tU+nekoQsc7bgQwytTuoj8omR9vt9/51WlIoJbEJf3h8WbJN+RrbrLIliQUFvtTHTMUXNA8VupjfcvCOlklDX1hvP+FeJJNzHO/HsnJudaAUZCp84j8h+pKbMIsqiQF54Bae/gCcquDTPQFEo5Qi8WgRU74gkoWxA/nopFK2Y/IMwowncLcZW6jdD2k/lY0McDaThWwCmwqLI7+Mh0b3JCgwz6DlIjvg5uKeKV4Q+1P+4A3f9aw7nfT4433gQaEx9amrSWG1GItKiNR+/QW5QWJaVw==
  template:
    metadata:
      name: alertmanager-pagerduty-key
      namespace: monitoring
