apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-pagerduty-key
  namespace: monitoring
spec:
  encryptedData:
    integration-key: AgCbH2FLNDFiHtbhgHjlXF5LgIqPViH6TeoQEJANbaajcKi9qyk7KFgVH3VlRcarj1MqqHwvlBknaut/yGi6ppF1+J9urzXr8e7dfrdSBqw/diJkdVAjlMLKSHpGXGqupxbcfDFTagix0Vt7yvsXGieEJFgDddKB65GMsnWeiuP9Q7k5/XAw+EXSJnq2dW3cKahbQDsT15dv9HhM5Awc1OQPPAjOWCdjOrFJCarL1xRQ4JbYO+9zOc5lOedYBlntGU+wL4UyKAJMEy/MLLNkAAKoZnP3f5mgQiYBHFJHsr03b9Xt+QuZXVaooUMNyMM4Lw/IgW5XV+auYNavHOEXsHGk/1bSmGwA/KWy94nB2CS4P33ybAiwSUSWJo1d2/HsXoh7tWbtohiTtirfmxjO9yFe/cQKSSuB87g+tZJ/B8OfmYqY2VC8GdoneQrM2bMSo+J122kjq3cxyal41hx0JVen4Ak9rIRQYeIZ34K4n199MgKAsDvClTWq5QGsJ0kiDNxipvOUEIvLSAjiQZGW4iw3jvCW81e9z16lrigPBgHQB2wJuxO2eAz8aCgpOUnaXboD6D6Rx6krO92J6ye+vyoWFgBswg7oCM+HBHkPRtr6QobmsPJFq1U9PWuxY2N4S0Qac8naXNtvbMCov/TBbK7d/XgoePIxLdUiS9BmUHkftnRarnxKYE1IFgYgx6CBGtXbfYB2dbd4g8kpfUG3axd8kw8p+ZMHhYBw3osJP87hkA==
  template:
    metadata:
      annotations:
        rotated-at: "2025-11-23T06:13:31Z"
        rotated-by: github-actions
      creationTimestamp: null
      name: alertmanager-pagerduty-key
      namespace: monitoring
    type: Opaque
---
