---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-pagerduty-key
  namespace: monitoring
spec:
  encryptedData:
    integration-key: AgAsxQBqfMPsgA/X6Yi32uOuZ65iFFu9P+gzSrotrBm0pf8llqZ76tgQh2UhX6KV+KVOsmsr0nL2TnNsHAwQV9gHBIDhqJo0cMYoZFS3U/sd0AQDO7b7a42YfnoWepuNzPVkkTtD1EtwJJMxcm427Qbaf3aQk4o4ve8/Gd0aaZnweGLUdhHLlLQHLzP3IMZwEAIZ/vb/E0J2r9W78iRNwJW5bQD+CUcYfqv/WjHjtHCJOVwcVjIaS5sNc8ic7FRAWUIos2kQ5MH55x/q2B1M+yWX4+G/d7mMtYIPi8UetKY+A+KoRkf7A56fNgoSM9lXkt+ssvHwukX9+dMM5I+LBvRTRoJ2Y3/4BmMqigqSSjBWhcUJLVzXaZxKd3WQxWmV3Jc2FbnQDym4DY8dxNUMNGnkiaR/3AokZ5W+ji4VP2iw0CuG9aY6zMCIe4AbMiVG2WwHaB/Ps3QZcwJOlQbsjRhXMVDIxG13CvFJxuLT2gqkbAEGmNo78qXRgBElwlVkm1UPgmhhTK2mISJQpHTyYhPOto2rJn8LpAwQKGCW3QZoA/wD4YJy99r0DNit4sDlzkTBLIpNZe6F6L1SgCxvXlYUayqO2zmi1TatqZmEfzaNQY24rdazIn4gvjFeji/X/zaLKXK9n3nxW4k6cR39HU35iAAOMfg/cEzgWziL5/Oe2EGQyUH9cetxLUuFjqbHs/7b0x73ZGvPBOB+yV7tZj3kBMvmDyIMWIene7zYHl+jLw==
  template:
    metadata:
      name: alertmanager-pagerduty-key
      namespace: monitoring
