---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-pagerduty-key
  namespace: monitoring
spec:
  encryptedData:
    integration-key: AgCn93m4mCO2h/E8D/0T8RVC28Iap/9cDBlGe+gjp8HDZnjycB2Ju2XB56Zla30AKHtvMQfJHEJjI6s20G/dhUDqTnOAn+aCgIvKvk22034XQaC+rlGjb63LDCRQ3BySrJmePe6vkqcl512hTY4eu2MKybhtbwplaKoRHrdrcIE5pwjm9D/lwQJw+wwqKeYrMZpvS1nKRoutyAN7H1MlOSTpO0NXonyvTVn88FWed9hH9UQ34nCekUkS1Xq/Q0NbCpBU9Xsx1CuqaJetpeskb27EPvgUDbWItHJ9R/NebcooEzpbexOiJJiHq6u4DDsblIAdWQJcX1zLEVv5bRtsnpEArN0B4ngGA3s7bZNvnXtWNUVg1l0GgFog71GxmGXPngxBnQqDg3PP+1H/lqNjZ4LyRu/z7JYUhPOhIUFrNP5/jHTU3MjwhJCQYtxupsrTwKTam+mPZcLwl5kAk3gMi6tvYPjRUgRptfDxrK3vm5ukDYzr+NQWRncblJGHSx8KoROLs4/++8KsDTsc2sxCT1nK42PC4r4NcF6mYTxcMZSW3y5poycobj1BPVb0IUXVYQ3MoJTUzofjIWE4LkkiAFq8EDSAX14/5KuRkhG8f7u1QMslpK6mT9ZH1YT4dzhQYWkMob2druTIiJXrVBeWwsSukdBFWLcxk3FskLCHrNncdjAPvxjuq5FmChj0q89QaKHFJf+DZm8S5oDOV8/YV2ze7PcfUiWqE1JOA6WhjJH8Qg==
  template:
    metadata:
      name: alertmanager-pagerduty-key
      namespace: monitoring
