---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-pagerduty-key
  namespace: monitoring
spec:
  encryptedData:
    integration-key: AgAmxQdeOispixdt5hXIlSz0E3sF1Ue1TWaTEhvUrQgBItJMoYzusfH9C+aY3mvp6SJowyzP7lt1yYZsYsUZNFV4GliWrk39UaMv3jsO0MQCi8gxpu995c+QbWXZJDJsZc3tQ5rbjC3FQgSCHAt3XPYyaBVjEmItlBq2QDdv87Au42S+bvIT+oEmTUkGnAys8dTcikKmDEuqX3T8PNALgBWvxRZySHOZ32NIK8qceF1daxDiV3Tmo+Q77RFKZkEcXCYWYGFY68Yj5OhMquXxR0mZbGo8kdCUV1zVkziISkJ63CVuB1J7p8nIBP2cIXPeWTH82prnulYSMStHCKhm6MJ3H+ze046JmbtgbEPqNMoBhSK9i0M4xWAJlspnfIw6WJN7cLhcj0Vos3EVpJf2NewK22y9XahjYldnqLM+IGQsn6RmN35APeO09p6IzAuPvMEYEcqpsudkqtZBzHo8QisZBHL4QvXDN5Q8LMj5RpSTbJcjO+i1DdVIsrERevtjrL0Vc60q11aBgkFXt0FhT+jGpv+X2cV0+I770DASjRea5GMAdOXnXn2ZYXahC3iRmpMsplQaQmeEshXy7cbYtSwFXPGWdbmjmnWhUG3ne9Rfi02aOwdR26SggTDlF/ae2Bmwzr6sssx3fbTblZu+3XHjm3BtujKM4A2LyfMJLViVToq1z6R/UtmmiVq6Gue69J6kzGOJ3t+gcYx3r/srO/CJQFGkO1QUXjzOqbXo2av72A==
  template:
    metadata:
      name: alertmanager-pagerduty-key
      namespace: monitoring
