apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-pagerduty-key
  namespace: monitoring
spec:
  encryptedData:
    integration-key: AgBCQdYMXXBOe2DPtnLZo6kcw4KmfAlVflQ6L3twu32ExtO3EmkadYp2crwKatauJsH0ET6EKJgDFSTIOa8qDr8y4KcVSGM3WjloZhO8minTkYSrfS+NB03qvqRsWLuP6lL/AdG8T4E+qeGh6cKrSzV9w4oTChlNVWVa2iCQx5yhwZHk2L6G1cS80fI/Yfmz/ShjFU/S+agzqTQKTQcO+VBBMO0vuxh6m9kuqkf4TKgaB/Sikb/Jbwh7NG9fltwaHdrws14SMgDaVOx/HR4zohMsx/Mxg4rVzADdgv+QTjpRFzQZf1gyfupt7w7bHfgCPwiuuyEgKvpf8fF5AAxxxlTkYCOOPuPf2APD1V6VWfgCzAmeT1X+E5NERGCsV6fSl7ygiYuSgljzJtWSw1yProqDulSCJ0uUa5DQqoK4Sdipz+bxnU1jVsWJh8MxlH44XmGLliAZ1kXunAW9tk8KzuTAF3KdsoqtwkUHjIyiKDzwZX3MoeoFZAdwdp3HPILQnfg9BwPxnoRBCtZ6KyMa5XgrT+P3HfQR4ZlrHJMhujAjZNgt9sViSqgqdpRd1MIBR0eqKfDWuhS6/PbQ5Df/pHMBUhNKLGl7hpGNeBI9rWewFWhY/8CX0uakUa16mXfBOBGeQwiBe7AZgVTAs7qD2fWbjRiLbF+KoLL7xchIIdH7bXdFxAK9CgSNWM2FTjz3vdP/t8TKdRbUbGzrOnC3Xc61TVzSVKQ0UtnWCSj/t3FNOA==
  template:
    metadata:
      annotations:
        rotated-at: "2025-11-23T07:00:19Z"
        rotated-by: github-actions
      creationTimestamp: null
      name: alertmanager-pagerduty-key
      namespace: monitoring
    type: Opaque
---
